/home/icaro/aom/build/aomenc_gprof_noOPT -p 1 -t 1 --psnr -v --fps=50/1 -w 416 -h 240 --lag-in-frames=0 --min-q=34 --max-q=42 --limit=30 --rt --tune=psnr --end-usage=q --min-gf-interval=16 --max-gf-interval=16 -b 8 -o /home/icaro/pesquisa_ucpel/output_AV1/local/gpbin/BasketballPass_416x240_50_qp37.bin /home/icaro/origCfP/BasketballPass_416x240_50.yuv 2> /home/icaro/pesquisa_ucpel/output_AV1/local/gpout/BasketballPass_416x240_50.yuv_qp37_av1gprof_noOPT_out && gprof /home/icaro/aom/build/aomenc_gprof_noOPT /home/icaro/pesquisa_ucpel/codes/run-sh/aom/gmon.out > /home/icaro/pesquisa_ucpel/output_AV1/local/gprof/gprof_BasketballPass_416x240_50.yuv_qp37_av1gprof_noOPT.txt
echo "DONE"
/home/icaro/aom/build/aomenc_gprof_noOPT -p 1 -t 1 --psnr -v --fps=50/1 -w 416 -h 240 --lag-in-frames=0 --min-q=34 --max-q=42 --limit=30 --rt --tune=psnr --end-usage=q --min-gf-interval=16 --max-gf-interval=16 -b 8 -o /home/icaro/pesquisa_ucpel/output_AV1/local/gpbin/BlowingBubbles_416x240_50_qp37.bin /home/icaro/origCfP/BlowingBubbles_416x240_50.yuv 2> /home/icaro/pesquisa_ucpel/output_AV1/local/gpout/BlowingBubbles_416x240_50.yuv_qp37_av1gprof_noOPT_out && gprof /home/icaro/aom/build/aomenc_gprof_noOPT /home/icaro/pesquisa_ucpel/codes/run-sh/aom/gmon.out > /home/icaro/pesquisa_ucpel/output_AV1/local/gprof/gprof_BlowingBubbles_416x240_50.yuv_qp37_av1gprof_noOPT.txt
echo "DONE"
/home/icaro/aom/build/aomenc_gprof_noOPT -p 1 -t 1 --psnr -v --fps=60/1 -w 416 -h 240 --lag-in-frames=0 --min-q=34 --max-q=42 --limit=30 --rt --tune=psnr --end-usage=q --min-gf-interval=16 --max-gf-interval=16 -b 8 -o /home/icaro/pesquisa_ucpel/output_AV1/local/gpbin/BQSquare_416x240_60_qp37.bin /home/icaro/origCfP/BQSquare_416x240_60.yuv 2> /home/icaro/pesquisa_ucpel/output_AV1/local/gpout/BQSquare_416x240_60.yuv_qp37_av1gprof_noOPT_out && gprof /home/icaro/aom/build/aomenc_gprof_noOPT /home/icaro/pesquisa_ucpel/codes/run-sh/aom/gmon.out > /home/icaro/pesquisa_ucpel/output_AV1/local/gprof/gprof_BQSquare_416x240_60.yuv_qp37_av1gprof_noOPT.txt
echo "DONE"
/home/icaro/aom/build/aomenc_gprof_noOPT -p 1 -t 1 --psnr -v --fps=30/1 -w 416 -h 240 --lag-in-frames=0 --min-q=34 --max-q=42 --limit=30 --rt --tune=psnr --end-usage=q --min-gf-interval=16 --max-gf-interval=16 -b 8 -o /home/icaro/pesquisa_ucpel/output_AV1/local/gpbin/RaceHorses_416x240_30_qp37.bin /home/icaro/origCfP/RaceHorses_416x240_30.yuv 2> /home/icaro/pesquisa_ucpel/output_AV1/local/gpout/RaceHorses_416x240_30.yuv_qp37_av1gprof_noOPT_out && gprof /home/icaro/aom/build/aomenc_gprof_noOPT /home/icaro/pesquisa_ucpel/codes/run-sh/aom/gmon.out > /home/icaro/pesquisa_ucpel/output_AV1/local/gprof/gprof_RaceHorses_416x240_30.yuv_qp37_av1gprof_noOPT.txt
echo "DONE"
/home/icaro/aom/build/aomenc_gprof_noOPT -p 1 -t 1 --psnr -v --fps=50/1 -w 416 -h 240 --lag-in-frames=0 --min-q=29 --max-q=37 --limit=30 --rt --tune=psnr --end-usage=q --min-gf-interval=16 --max-gf-interval=16 -b 8 -o /home/icaro/pesquisa_ucpel/output_AV1/local/gpbin/BasketballPass_416x240_50_qp32.bin /home/icaro/origCfP/BasketballPass_416x240_50.yuv 2> /home/icaro/pesquisa_ucpel/output_AV1/local/gpout/BasketballPass_416x240_50.yuv_qp32_av1gprof_noOPT_out && gprof /home/icaro/aom/build/aomenc_gprof_noOPT /home/icaro/pesquisa_ucpel/codes/run-sh/aom/gmon.out > /home/icaro/pesquisa_ucpel/output_AV1/local/gprof/gprof_BasketballPass_416x240_50.yuv_qp32_av1gprof_noOPT.txt
echo "DONE"
/home/icaro/aom/build/aomenc_gprof_noOPT -p 1 -t 1 --psnr -v --fps=50/1 -w 416 -h 240 --lag-in-frames=0 --min-q=29 --max-q=37 --limit=30 --rt --tune=psnr --end-usage=q --min-gf-interval=16 --max-gf-interval=16 -b 8 -o /home/icaro/pesquisa_ucpel/output_AV1/local/gpbin/BlowingBubbles_416x240_50_qp32.bin /home/icaro/origCfP/BlowingBubbles_416x240_50.yuv 2> /home/icaro/pesquisa_ucpel/output_AV1/local/gpout/BlowingBubbles_416x240_50.yuv_qp32_av1gprof_noOPT_out && gprof /home/icaro/aom/build/aomenc_gprof_noOPT /home/icaro/pesquisa_ucpel/codes/run-sh/aom/gmon.out > /home/icaro/pesquisa_ucpel/output_AV1/local/gprof/gprof_BlowingBubbles_416x240_50.yuv_qp32_av1gprof_noOPT.txt
echo "DONE"
/home/icaro/aom/build/aomenc_gprof_noOPT -p 1 -t 1 --psnr -v --fps=60/1 -w 416 -h 240 --lag-in-frames=0 --min-q=29 --max-q=37 --limit=30 --rt --tune=psnr --end-usage=q --min-gf-interval=16 --max-gf-interval=16 -b 8 -o /home/icaro/pesquisa_ucpel/output_AV1/local/gpbin/BQSquare_416x240_60_qp32.bin /home/icaro/origCfP/BQSquare_416x240_60.yuv 2> /home/icaro/pesquisa_ucpel/output_AV1/local/gpout/BQSquare_416x240_60.yuv_qp32_av1gprof_noOPT_out && gprof /home/icaro/aom/build/aomenc_gprof_noOPT /home/icaro/pesquisa_ucpel/codes/run-sh/aom/gmon.out > /home/icaro/pesquisa_ucpel/output_AV1/local/gprof/gprof_BQSquare_416x240_60.yuv_qp32_av1gprof_noOPT.txt
echo "DONE"
/home/icaro/aom/build/aomenc_gprof_noOPT -p 1 -t 1 --psnr -v --fps=30/1 -w 416 -h 240 --lag-in-frames=0 --min-q=29 --max-q=37 --limit=30 --rt --tune=psnr --end-usage=q --min-gf-interval=16 --max-gf-interval=16 -b 8 -o /home/icaro/pesquisa_ucpel/output_AV1/local/gpbin/RaceHorses_416x240_30_qp32.bin /home/icaro/origCfP/RaceHorses_416x240_30.yuv 2> /home/icaro/pesquisa_ucpel/output_AV1/local/gpout/RaceHorses_416x240_30.yuv_qp32_av1gprof_noOPT_out && gprof /home/icaro/aom/build/aomenc_gprof_noOPT /home/icaro/pesquisa_ucpel/codes/run-sh/aom/gmon.out > /home/icaro/pesquisa_ucpel/output_AV1/local/gprof/gprof_RaceHorses_416x240_30.yuv_qp32_av1gprof_noOPT.txt
echo "DONE"
/home/icaro/aom/build/aomenc_gprof_noOPT -p 1 -t 1 --psnr -v --fps=50/1 -w 416 -h 240 --lag-in-frames=0 --min-q=24 --max-q=32 --limit=30 --rt --tune=psnr --end-usage=q --min-gf-interval=16 --max-gf-interval=16 -b 8 -o /home/icaro/pesquisa_ucpel/output_AV1/local/gpbin/BasketballPass_416x240_50_qp27.bin /home/icaro/origCfP/BasketballPass_416x240_50.yuv 2> /home/icaro/pesquisa_ucpel/output_AV1/local/gpout/BasketballPass_416x240_50.yuv_qp27_av1gprof_noOPT_out && gprof /home/icaro/aom/build/aomenc_gprof_noOPT /home/icaro/pesquisa_ucpel/codes/run-sh/aom/gmon.out > /home/icaro/pesquisa_ucpel/output_AV1/local/gprof/gprof_BasketballPass_416x240_50.yuv_qp27_av1gprof_noOPT.txt
echo "DONE"
/home/icaro/aom/build/aomenc_gprof_noOPT -p 1 -t 1 --psnr -v --fps=50/1 -w 416 -h 240 --lag-in-frames=0 --min-q=24 --max-q=32 --limit=30 --rt --tune=psnr --end-usage=q --min-gf-interval=16 --max-gf-interval=16 -b 8 -o /home/icaro/pesquisa_ucpel/output_AV1/local/gpbin/BlowingBubbles_416x240_50_qp27.bin /home/icaro/origCfP/BlowingBubbles_416x240_50.yuv 2> /home/icaro/pesquisa_ucpel/output_AV1/local/gpout/BlowingBubbles_416x240_50.yuv_qp27_av1gprof_noOPT_out && gprof /home/icaro/aom/build/aomenc_gprof_noOPT /home/icaro/pesquisa_ucpel/codes/run-sh/aom/gmon.out > /home/icaro/pesquisa_ucpel/output_AV1/local/gprof/gprof_BlowingBubbles_416x240_50.yuv_qp27_av1gprof_noOPT.txt
echo "DONE"
/home/icaro/aom/build/aomenc_gprof_noOPT -p 1 -t 1 --psnr -v --fps=60/1 -w 416 -h 240 --lag-in-frames=0 --min-q=24 --max-q=32 --limit=30 --rt --tune=psnr --end-usage=q --min-gf-interval=16 --max-gf-interval=16 -b 8 -o /home/icaro/pesquisa_ucpel/output_AV1/local/gpbin/BQSquare_416x240_60_qp27.bin /home/icaro/origCfP/BQSquare_416x240_60.yuv 2> /home/icaro/pesquisa_ucpel/output_AV1/local/gpout/BQSquare_416x240_60.yuv_qp27_av1gprof_noOPT_out && gprof /home/icaro/aom/build/aomenc_gprof_noOPT /home/icaro/pesquisa_ucpel/codes/run-sh/aom/gmon.out > /home/icaro/pesquisa_ucpel/output_AV1/local/gprof/gprof_BQSquare_416x240_60.yuv_qp27_av1gprof_noOPT.txt
echo "DONE"
/home/icaro/aom/build/aomenc_gprof_noOPT -p 1 -t 1 --psnr -v --fps=30/1 -w 416 -h 240 --lag-in-frames=0 --min-q=24 --max-q=32 --limit=30 --rt --tune=psnr --end-usage=q --min-gf-interval=16 --max-gf-interval=16 -b 8 -o /home/icaro/pesquisa_ucpel/output_AV1/local/gpbin/RaceHorses_416x240_30_qp27.bin /home/icaro/origCfP/RaceHorses_416x240_30.yuv 2> /home/icaro/pesquisa_ucpel/output_AV1/local/gpout/RaceHorses_416x240_30.yuv_qp27_av1gprof_noOPT_out && gprof /home/icaro/aom/build/aomenc_gprof_noOPT /home/icaro/pesquisa_ucpel/codes/run-sh/aom/gmon.out > /home/icaro/pesquisa_ucpel/output_AV1/local/gprof/gprof_RaceHorses_416x240_30.yuv_qp27_av1gprof_noOPT.txt
echo "DONE"
/home/icaro/aom/build/aomenc_gprof_noOPT -p 1 -t 1 --psnr -v --fps=50/1 -w 416 -h 240 --lag-in-frames=0 --min-q=19 --max-q=27 --limit=30 --rt --tune=psnr --end-usage=q --min-gf-interval=16 --max-gf-interval=16 -b 8 -o /home/icaro/pesquisa_ucpel/output_AV1/local/gpbin/BasketballPass_416x240_50_qp22.bin /home/icaro/origCfP/BasketballPass_416x240_50.yuv 2> /home/icaro/pesquisa_ucpel/output_AV1/local/gpout/BasketballPass_416x240_50.yuv_qp22_av1gprof_noOPT_out && gprof /home/icaro/aom/build/aomenc_gprof_noOPT /home/icaro/pesquisa_ucpel/codes/run-sh/aom/gmon.out > /home/icaro/pesquisa_ucpel/output_AV1/local/gprof/gprof_BasketballPass_416x240_50.yuv_qp22_av1gprof_noOPT.txt
echo "DONE"
/home/icaro/aom/build/aomenc_gprof_noOPT -p 1 -t 1 --psnr -v --fps=50/1 -w 416 -h 240 --lag-in-frames=0 --min-q=19 --max-q=27 --limit=30 --rt --tune=psnr --end-usage=q --min-gf-interval=16 --max-gf-interval=16 -b 8 -o /home/icaro/pesquisa_ucpel/output_AV1/local/gpbin/BlowingBubbles_416x240_50_qp22.bin /home/icaro/origCfP/BlowingBubbles_416x240_50.yuv 2> /home/icaro/pesquisa_ucpel/output_AV1/local/gpout/BlowingBubbles_416x240_50.yuv_qp22_av1gprof_noOPT_out && gprof /home/icaro/aom/build/aomenc_gprof_noOPT /home/icaro/pesquisa_ucpel/codes/run-sh/aom/gmon.out > /home/icaro/pesquisa_ucpel/output_AV1/local/gprof/gprof_BlowingBubbles_416x240_50.yuv_qp22_av1gprof_noOPT.txt
echo "DONE"
/home/icaro/aom/build/aomenc_gprof_noOPT -p 1 -t 1 --psnr -v --fps=60/1 -w 416 -h 240 --lag-in-frames=0 --min-q=19 --max-q=27 --limit=30 --rt --tune=psnr --end-usage=q --min-gf-interval=16 --max-gf-interval=16 -b 8 -o /home/icaro/pesquisa_ucpel/output_AV1/local/gpbin/BQSquare_416x240_60_qp22.bin /home/icaro/origCfP/BQSquare_416x240_60.yuv 2> /home/icaro/pesquisa_ucpel/output_AV1/local/gpout/BQSquare_416x240_60.yuv_qp22_av1gprof_noOPT_out && gprof /home/icaro/aom/build/aomenc_gprof_noOPT /home/icaro/pesquisa_ucpel/codes/run-sh/aom/gmon.out > /home/icaro/pesquisa_ucpel/output_AV1/local/gprof/gprof_BQSquare_416x240_60.yuv_qp22_av1gprof_noOPT.txt
echo "DONE"
/home/icaro/aom/build/aomenc_gprof_noOPT -p 1 -t 1 --psnr -v --fps=30/1 -w 416 -h 240 --lag-in-frames=0 --min-q=19 --max-q=27 --limit=30 --rt --tune=psnr --end-usage=q --min-gf-interval=16 --max-gf-interval=16 -b 8 -o /home/icaro/pesquisa_ucpel/output_AV1/local/gpbin/RaceHorses_416x240_30_qp22.bin /home/icaro/origCfP/RaceHorses_416x240_30.yuv 2> /home/icaro/pesquisa_ucpel/output_AV1/local/gpout/RaceHorses_416x240_30.yuv_qp22_av1gprof_noOPT_out && gprof /home/icaro/aom/build/aomenc_gprof_noOPT /home/icaro/pesquisa_ucpel/codes/run-sh/aom/gmon.out > /home/icaro/pesquisa_ucpel/output_AV1/local/gprof/gprof_RaceHorses_416x240_30.yuv_qp22_av1gprof_noOPT.txt
echo "DONE"
